### ISSUE TITLE
D in SOLID does not stand for DRY. :)

### ISSUE THREAD

**Issue by jbrains** [fluffynuts/tdd-101#1]
> the "D" in SOLID stands for "Don't Repeat Yourself"

It's the Dependency Inversion Principle. :)

**Comment by fluffynuts** [comment]
Thanks @jbrains. I wish I was automatically notified of issues in my own repos - I'm finally going through repos and updating all my own ones to follow everything, because I miss out on interesting issues ):

**Comment by jbrains** [comment]
You're welcome, but even so, "Dependency Inversion" is not the same as "Dependency Injection". DIP is a principle regarding which dependencies tend to be healthier in designs; DI is a technique for weakening dependencies. DI supports DIP, but we can apply DIP without DI.

Here's one very common example: a function that depends on the system clock. This dependency is _easy_, but not _simple_, because that function now depends on _implicit_ and _external_ and _constantly changing_ data. The only way to make it worse would be if talking to the system clock were _slow_ and/or _asynchronous_. :) This dependency interferes with our ability to make tests reliable by making them repeatable/predictable.

We can weaken the dependency by injecting a Virtual Clock, which we can stub with predictable values in our tests. We would then implement an Adapter to the system clock that implements our Virtual Clock abstraction (interface, lambda expression, whatever). The Virtual Clock is essentially a supplier of Timestamp values with certain very complicated properties. (Time is hard.) This is an example of using DI to apply DIP.

Often we can do this more simply. Suppose this function doesn't rely on the _passage_ of time, but merely invokes `now()` once. In this case, we could invert the dependency by pulling `now()` one level up the call stack. This changes the function so that it accepts a Timestamp value as an argument instead of invoking the global `now()` function directly to get a Timestamp. The invoker of this function takes the responsibility for invoking `now()` and then passing that value into our function. Our tests can pass any Timestamp value that's convenient for them, while our production code can invoke `now()` when it needs to. This applies the DIP with no DI. 

We generally have two options when applying DIP in order to weaken a dependency:

1. Invert only the dependency on the implementation choice: inject an abstraction so that different clients can pass different implementations. This is DI.
2. Invert the dependency on the behavior entirely: in this case, replace Supplier of X with X, so that the function doesn't even know that the X "comes from somewhere". This doesn't require DI.

The DI approach is more common in OOP; the direct inversion approach is more common in FP. Both are ways to reduce the overall dependency on details (one formulation of DIP), but only the first one involves DI. The direct inversion approach simplifies the lower layers of the code more radically, which makes it arguably more effective, but many (most?) of today's professional programmers feel more comfortable with injecting an abstraction than they feel with inverting the entire dependency. Fortunately, it's relatively easy to refactor from the first to the second, so with enough repetition, programmers can become comfortable with the more-radical approach.

I hope this helps.

**Comment by fluffynuts** [comment]
I see where you're coming from, but some of it seems a little like splitting hairs to be honest (esp considering the audience).

In the case of the clock example above, the dependency wasn't so much inverted as _removed_: the function now no longer depends on the concept of "what time is it now", but instead is given a timestamp - a data value. I do see the difference between that and injecting a virtual clock conceptually, of course. I'll probably update the doc to be in line with with the nomenclature at wikipedia, but for all intents and purposes, Dependency Inversion implies Dependency Injection, especially within the scope of the code examples.
